#pragma kernel Test1by1by1
#pragma kernel Test8by1by8
#pragma kernel Test8by8by8

RWStructuredBuffer<uint> Data;
float3 Size;

int GetIndex(float3 position) {
	return (uint)(Size.z * position.z + position.y * (Size.x * Size.z) + position.x);
}

[numthreads(1,1,1)]
void Test1by1by1 (uint3 id : SV_DispatchThreadID)
{
	uint index = GetIndex(id); 
	Data[index] = index;  
}

[numthreads(8,1,8)]
void Test8by1by8 (uint3 id : SV_DispatchThreadID)
{
	uint index = GetIndex(id); 
	Data[index] = index;  
}

[numthreads(8,8,8)]
void Test8by8by8 (uint3 id : SV_DispatchThreadID)
{
	uint index = GetIndex(id); 
	Data[index] = index;  
}
